name: Test suite

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-22.04
    name: Test suite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          package_file: .github/tl_packages
      - name: Run l3build
        run: l3build check --show-log-on-error -q -H
      - name: Archive failed test output
        if: ${{ always() }}
        uses: zauguin/l3build-failure-artifacts@v1
        with:
          name: testfiles
  docs:
    runs-on: ubuntu-22.04
    name: Documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          package_file: .github/tl_packages
      - name: Run l3build
        run: l3build doc -q -H
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: "**/*.pdf"
