name: Release

on:
  push:
    tags: "*"

jobs:
  l3build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          package_file: .github/tl_packages
      - name: Run l3build
        run: l3build ctan --show-log-on-error -H
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: "build/distrib/ctan/*.zip"

  github:
    runs-on: ubuntu-22.04
    needs:
      - l3build
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: Package
      - name: Create GitHub release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        with:
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

  ctan-validate:
    runs-on: ubuntu-22.04
    needs:
      - l3build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: Package
      - name: Validate CTAN package
        uses: ./.github/actions/ctan-upload
        with:
          uploader: Dummy Name
          email: dryrun@example.com
          filename: lua-ul-ctan.zip
          dry-run: true
